import type { NextPage } from 'next'
import Head from 'next/head'
import StageSelectHeader from "../components/StageSelectHeader";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <StageSelectHeader />
      </main>
    </div>
  )
}

export default Home
